CI: patch setuptools to use pkgutil.ImpImporter only if it exists.
Patch stolen from:
https://github.com/pypa/setuptools/commit/6653e747c3815b14

Fixes:

    Traceback (most recent call last):
      ...
      File ".../lib/python3.12/site-packages/pkg_resources/__init__.py", line 2158, in <module>
        register_finder(pkgutil.ImpImporter, find_on_path)
                        ^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

pkgutil.ImpImporter was removed in Python 3.12.