CI: install zombie-imp if needed.
Fixes:

    Traceback (most recent call last):
      ...
      File ".../lib/python3.12/site-packages/nose/importer.py", line 12, in <module>
        from imp import find_module, load_module, acquire_lock, release_lock
    ModuleNotFoundError: No module named 'imp'

The imp module was removed in Python 3.12.