tests/test_stdlib: on Windows, check only random sample of modules.
We can't test all the stdlib modules easily, because Windows has tight
limits on command-line length.

Fixes:

    ======================================================================
    ERROR: test_stdlib.test
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
        self.test(*self.arg)
      File "...\pydiatra\tests\test_stdlib.py", line 45, in test
        tools.run_pydiatra(paths, expected=None, parallel=parallel)
      File "...\pydiatra\tests\tools.py", line 64, in run_pydiatra
        s.decode('UTF-8').splitlines()
      File "C:\Python27\lib\subprocess.py", line 394, in __init__
        errread, errwrite)
      File "C:\Python27\lib\subprocess.py", line 652, in _execute_child
        startupinfo)
    WindowsError: [Error 87] Invalid parameter

    ----------------------------------------------------------------------