tests/test_confut_import: fix PYTHONPATH mangling.
Fixes:

    ======================================================================
    ERROR: test_confut_import.test
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File ".../pydiatra/tests/test_confut_import.py", line 50, in test
        PYTHONPATH[:0] = tmpdir
    TypeError: 'str' object does not support item assignment

    ----------------------------------------------------------------------