tests/run-tests: add nose version check.
This improves error message when running against nose < 0.11,
which didn't support addplugins.

Before:

    TypeError: __init__() got an unexpected keyword argument 'addplugins'

After:

    RuntimeError: nose >= 0.11 is required