Add Python version check.
Before:

    $ python2.5 ./py2diatra
    .../pydiatra/main.py:40: Warning: 'as' will become a reserved keyword in Python 2.6
    Traceback (most recent call last):
      File "./py2diatra", line 2, in <module>
        import pydiatra.main
      File ".../pydiatra/main.py", line 40
        except ImportError as exc:
                            ^
    SyntaxError: invalid syntax

After:

    $ python2.5 ./py2diatra
    Traceback (most recent call last):
      File "./py2diatra", line 2, in <module>
        import pydiatra.main
      File ".../pydiatra/__init__.py", line 5
        b''  # Python >= 2.6 is required
          ^
    SyntaxError: invalid syntax